import Head from 'next/head';
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Electric Cars, Solar & Clean Energy | Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Hero />
    </>
  )
}
